"""initial_tables

Revision ID: df1c2aa7702d
Revises: 
Create Date: 2026-09-21 13:56:31.387965

"""
from typing import Sequence, Union

from alembic import op
import geoalchemy2
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'df1c2aa7702d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    op.execute("CREATE EXTENSION IF NOT EXISTS timescaledb")
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")

    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('occurred_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor_type', sa.Enum('user', 'system', 'ai_agent', name='actor_type_enum'), nullable=False),
    sa.Column('actor_id', sa.Text(), nullable=True),
    sa.Column('action', sa.Enum('create', 'update', 'delete', 'read', 'login', 'export', 'verdict_change', name='audit_action_enum'), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('before_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('hash_chain_previous', sa.CHAR(length=64), nullable=True),
    sa.Column('event_hash', sa.CHAR(length=64), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("event_hash ~ '^[a-f0-9]{64}$'", name='chk_audit_log_event_hash'),
    sa.CheckConstraint("hash_chain_previous IS NULL OR hash_chain_previous ~ '^[a-f0-9]{64}$'", name='chk_audit_log_hash_previous'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_actor', 'audit_log', ['actor_type', 'actor_id'], unique=False)
    op.create_index('idx_audit_entity', 'audit_log', ['entity_type', 'entity_id'], unique=False)
    op.create_index('idx_audit_occurred_at', 'audit_log', ['occurred_at'], unique=False)
    op.create_table('environmental_data',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('variable', sa.Text(), nullable=False),
    sa.Column('valid_time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False, spatial_index=False), nullable=False),
    sa.Column('value', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'variable', 'valid_time', 'location', name='uq_env_source_var_time_loc')
    )
    op.create_index('idx_env_location', 'environmental_data', ['location'], unique=False, postgresql_using='gist')
    op.create_index('idx_env_source_var_time', 'environmental_data', ['source', 'variable', 'valid_time'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('job_type', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'completed', 'failed', name='job_status_enum'), server_default='queued', nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('idempotency_key', sa.Text(), nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('retry_count >= 0', name='chk_jobs_retry_count'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_jobs_idempotency')
    )
    op.create_index('idx_jobs_idempotency', 'jobs', ['idempotency_key'], unique=True)
    op.create_index('idx_jobs_status', 'jobs', ['status'], unique=False)
    op.create_index('idx_jobs_type', 'jobs', ['job_type'], unique=False)
    op.create_table('scenes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source_provider', sa.Text(), nullable=False),
    sa.Column('external_scene_id', sa.Text(), nullable=False),
    sa.Column('captured_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('ingested_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('footprint', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False, spatial_index=False), nullable=False),
    sa.Column('cloud_cover_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('wind_speed', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('wind_direction', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('storage_uri', sa.Text(), nullable=False),
    sa.Column('sha256', sa.CHAR(length=64), nullable=False),
    sa.Column('processing_status', sa.Enum('pending', 'pending_metadata', 'processing', 'processed', 'failed', name='scene_status_enum'), server_default='pending', nullable=False),
    sa.Column('source_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("sha256 ~ '^[a-f0-9]{64}$'", name='chk_scenes_sha256'),
    sa.CheckConstraint('cloud_cover_percentage IS NULL OR (cloud_cover_percentage >= 0 AND cloud_cover_percentage <= 100)', name='chk_scenes_cloud_cover'),
    sa.CheckConstraint('wind_direction IS NULL OR (wind_direction >= 0 AND wind_direction <= 360)', name='chk_scenes_wind_direction'),
    sa.CheckConstraint('wind_speed IS NULL OR wind_speed >= 0', name='chk_scenes_wind_speed'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_provider', 'external_scene_id', name='uq_scenes_provider_external')
    )
    op.create_index('idx_scenes_captured_at', 'scenes', ['captured_at'], unique=False)
    op.create_index('idx_scenes_footprint', 'scenes', ['footprint'], unique=False, postgresql_using='gist')
    op.create_index('idx_scenes_provider_external', 'scenes', ['source_provider', 'external_scene_id'], unique=True)
    op.create_table('vessels',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('mmsi', sa.Text(), nullable=True),
    sa.Column('imo', sa.Text(), nullable=True),
    sa.Column('vessel_name', sa.Text(), nullable=False),
    sa.Column('vessel_type', sa.Enum('crude_tanker', 'chemical_tanker', 'cargo', 'container', 'fishing', 'tanker_other', 'unknown', name='vessel_type_enum'), server_default='unknown', nullable=False),
    sa.Column('flag_country_code', sa.CHAR(length=2), nullable=True),
    sa.Column('deadweight_tonnage', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("imo IS NULL OR imo ~ '^[0-9]{7}$'", name='chk_vessels_imo_format'),
    sa.CheckConstraint("mmsi IS NULL OR mmsi ~ '^[0-9]{9}$'", name='chk_vessels_mmsi_format'),
    sa.CheckConstraint('deadweight_tonnage IS NULL OR deadweight_tonnage > 0', name='chk_vessels_deadweight_tonnage'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_vessels_imo', 'vessels', ['imo'], unique=True, postgresql_where=sa.text('imo IS NOT NULL'))
    op.create_index('idx_vessels_mmsi', 'vessels', ['mmsi'], unique=True, postgresql_where=sa.text('mmsi IS NOT NULL'))
    op.create_index('idx_vessels_type', 'vessels', ['vessel_type'], unique=False)
    op.create_table('ais_gaps',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('vessel_id', sa.UUID(), nullable=False),
    sa.Column('gap_start', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('gap_end', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('gap_duration_min', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('last_position', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False, spatial_index=False), nullable=False),
    sa.Column('next_position', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False, spatial_index=False), nullable=False),
    sa.Column('gap_center', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False, spatial_index=False), nullable=False),
    sa.Column('distance_from_coast_nm', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('is_open_water', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('gap_duration_min > 0', name='chk_ais_gaps_duration'),
    sa.CheckConstraint('gap_end > gap_start', name='chk_ais_gaps_time_order'),
    sa.ForeignKeyConstraint(['vessel_id'], ['vessels.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ais_gaps_gap_center', 'ais_gaps', ['gap_center'], unique=False, postgresql_using='gist')
    op.create_index('idx_ais_gaps_last_position', 'ais_gaps', ['last_position'], unique=False, postgresql_using='gist')
    op.create_index('idx_ais_gaps_next_position', 'ais_gaps', ['next_position'], unique=False, postgresql_using='gist')
    op.create_index('idx_ais_gaps_time', 'ais_gaps', ['gap_start', 'gap_end'], unique=False)
    op.create_index('idx_ais_gaps_vessel', 'ais_gaps', ['vessel_id'], unique=False)
    op.create_table('spills',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('scene_id', sa.UUID(), nullable=False),
    sa.Column('detected_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('spill_polygon', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False, spatial_index=False), nullable=False),
    sa.Column('area_sq_km', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('detection_model_name', sa.Text(), nullable=False),
    sa.Column('detection_model_version', sa.Text(), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('processing_run_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('detected', 'under_review', 'confirmed', 'rejected', name='spill_status_enum'), server_default='detected', nullable=False),
    sa.Column('reviewed_by', sa.Text(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('area_sq_km > 0', name='chk_spills_area_sq_km'),
    sa.CheckConstraint('confidence_score >= 0 AND confidence_score <= 1', name='chk_spills_confidence_score'),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_spills_scene', 'spills', ['scene_id'], unique=False)
    op.create_index('idx_spills_spill_polygon', 'spills', ['spill_polygon'], unique=False, postgresql_using='gist')
    op.create_index('idx_spills_status', 'spills', ['status'], unique=False)
    op.create_table('tracks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('vessel_id', sa.UUID(), nullable=False),
    sa.Column('recorded_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('position', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False, spatial_index=False), nullable=False),
    sa.Column('speed_knots', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('course_degrees', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('heading_degrees', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('navigational_status', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('source_record_id', sa.Text(), nullable=False),
    sa.Column('ingestion_batch_id', sa.UUID(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('course_degrees >= 0 AND course_degrees <= 360', name='chk_tracks_course_degrees'),
    sa.CheckConstraint('heading_degrees IS NULL OR (heading_degrees >= 0 AND heading_degrees <= 360)', name='chk_tracks_heading_degrees'),
    sa.CheckConstraint('speed_knots >= 0 AND speed_knots <= 100', name='chk_tracks_speed_knots'),
    sa.ForeignKeyConstraint(['vessel_id'], ['vessels.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', 'recorded_at'),
    sa.UniqueConstraint('source', 'source_record_id', 'recorded_at', name='uq_tracks_source')
    )
    op.create_index('idx_tracks_position', 'tracks', ['position'], unique=False, postgresql_using='gist')
    op.create_index('idx_tracks_recorded_at_brin', 'tracks', ['recorded_at'], unique=False, postgresql_using='brin')
    op.create_index('idx_tracks_vessel_time', 'tracks', ['vessel_id', sa.literal_column('recorded_at DESC')], unique=False)
    op.create_table('dossiers',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('scene_id', sa.UUID(), nullable=False),
    sa.Column('spill_id', sa.UUID(), nullable=True),
    sa.Column('dossier_version', sa.Text(), nullable=False),
    sa.Column('generated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('generated_by', sa.Text(), nullable=False),
    sa.Column('storage_uri', sa.Text(), nullable=False),
    sa.Column('sha256', sa.CHAR(length=64), nullable=False),
    sa.Column('evidence_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('draft', 'finalized', 'superseded', name='dossier_status_enum'), server_default='draft', nullable=False),
    sa.Column('supersedes_dossier_id', sa.UUID(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("sha256 ~ '^[a-f0-9]{64}$'", name='chk_dossiers_sha256'),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['spill_id'], ['spills.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supersedes_dossier_id'], ['dossiers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_dossiers_scene', 'dossiers', ['scene_id'], unique=False)
    op.create_index('idx_dossiers_status', 'dossiers', ['status'], unique=False)
    op.create_table('drift_runs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('scene_id', sa.UUID(), nullable=False),
    sa.Column('vessel_id', sa.UUID(), nullable=False),
    sa.Column('spill_id', sa.UUID(), nullable=True),
    sa.Column('simulation_version', sa.Text(), nullable=False),
    sa.Column('model_parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('run_fingerprint', sa.CHAR(length=64), nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('queued', 'running', 'completed', 'failed', name='drift_status_enum'), server_default='queued', nullable=False),
    sa.Column('output_storage_uri', sa.Text(), nullable=True),
    sa.Column('output_sha256', sa.CHAR(length=64), nullable=True),
    sa.Column('result_summary', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("output_sha256 IS NULL OR output_sha256 ~ '^[a-f0-9]{64}$'", name='chk_drift_runs_output_sha256'),
    sa.CheckConstraint("run_fingerprint ~ '^[a-f0-9]{64}$'", name='chk_drift_runs_fingerprint'),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['spill_id'], ['spills.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vessel_id'], ['vessels.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_fingerprint', name='uq_drift_runs_fingerprint')
    )
    op.create_index('idx_drift_runs_fingerprint', 'drift_runs', ['run_fingerprint'], unique=True)
    op.create_index('idx_drift_runs_scene', 'drift_runs', ['scene_id'], unique=False)
    op.create_index('idx_drift_runs_vessel', 'drift_runs', ['vessel_id'], unique=False)
    op.create_table('attribution_scores',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('drift_run_id', sa.UUID(), nullable=False),
    sa.Column('scoring_version', sa.Text(), nullable=False),
    sa.Column('cpa_score', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('dark_vessel_score', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('loitering_score', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('capacity_multiplier', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('draft_change_score', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('permutation_p_value', sa.Numeric(precision=6, scale=5), nullable=False),
    sa.Column('stability_index', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('total_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('verdict', sa.Enum('prosecutable', 'person_of_interest', 'insufficient_evidence', name='verdict_enum'), nullable=False),
    sa.Column('explanation', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('calculated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('capacity_multiplier = 0 OR capacity_multiplier = 1', name='chk_attribution_capacity_multiplier'),
    sa.CheckConstraint('cpa_score >= 0 AND cpa_score <= 1', name='chk_attribution_cpa_score'),
    sa.CheckConstraint('dark_vessel_score >= 0 AND dark_vessel_score <= 1', name='chk_attribution_dark_vessel_score'),
    sa.CheckConstraint('draft_change_score >= 0 AND draft_change_score <= 1', name='chk_attribution_draft_change_score'),
    sa.CheckConstraint('loitering_score >= 0 AND loitering_score <= 1', name='chk_attribution_loitering_score'),
    sa.CheckConstraint('permutation_p_value >= 0 AND permutation_p_value <= 1', name='chk_attribution_p_value'),
    sa.CheckConstraint('stability_index >= 0 AND stability_index <= 1', name='chk_attribution_stability_index'),
    sa.CheckConstraint('total_score >= 0 AND total_score <= 100', name='chk_attribution_total_score'),
    sa.ForeignKeyConstraint(['drift_run_id'], ['drift_runs.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('drift_run_id', 'scoring_version', name='uq_attribution_run_version')
    )
    op.create_index('idx_attribution_run_version', 'attribution_scores', ['drift_run_id', 'scoring_version'], unique=True)
    op.create_index('idx_attribution_total_score', 'attribution_scores', ['total_score'], unique=False)
    op.create_index('idx_attribution_verdict', 'attribution_scores', ['verdict'], unique=False)
    op.create_table('cpa_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('drift_run_id', sa.UUID(), nullable=False),
    sa.Column('vessel_id', sa.UUID(), nullable=False),
    sa.Column('min_distance_m', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cpa_timestamp', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('tcpa_seconds', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('vessel_position_at_cpa', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False, spatial_index=False), nullable=False),
    sa.Column('slick_position_at_cpa', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False, spatial_index=False), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('min_distance_m >= 0', name='chk_cpa_min_distance'),
    sa.ForeignKeyConstraint(['drift_run_id'], ['drift_runs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vessel_id'], ['vessels.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cpa_drift_run', 'cpa_events', ['drift_run_id'], unique=False)
    op.create_index('idx_cpa_events_slick_position_at_cpa', 'cpa_events', ['slick_position_at_cpa'], unique=False, postgresql_using='gist')
    op.create_index('idx_cpa_events_vessel_position_at_cpa', 'cpa_events', ['vessel_position_at_cpa'], unique=False, postgresql_using='gist')
    op.create_index('idx_cpa_vessel', 'cpa_events', ['vessel_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_cpa_vessel', table_name='cpa_events')
    op.drop_index('idx_cpa_events_vessel_position_at_cpa', table_name='cpa_events', postgresql_using='gist')
    op.drop_index('idx_cpa_events_slick_position_at_cpa', table_name='cpa_events', postgresql_using='gist')
    op.drop_index('idx_cpa_drift_run', table_name='cpa_events')
    op.drop_table('cpa_events')
    op.drop_index('idx_attribution_verdict', table_name='attribution_scores')
    op.drop_index('idx_attribution_total_score', table_name='attribution_scores')
    op.drop_index('idx_attribution_run_version', table_name='attribution_scores')
    op.drop_table('attribution_scores')
    op.drop_index('idx_drift_runs_vessel', table_name='drift_runs')
    op.drop_index('idx_drift_runs_scene', table_name='drift_runs')
    op.drop_index('idx_drift_runs_fingerprint', table_name='drift_runs')
    op.drop_table('drift_runs')
    op.drop_index('idx_dossiers_status', table_name='dossiers')
    op.drop_index('idx_dossiers_scene', table_name='dossiers')
    op.drop_table('dossiers')
    op.drop_index('idx_tracks_vessel_time', table_name='tracks')
    op.drop_index('idx_tracks_recorded_at_brin', table_name='tracks', postgresql_using='brin')
    op.drop_index('idx_tracks_position', table_name='tracks', postgresql_using='gist')
    op.drop_table('tracks')
    op.drop_index('idx_spills_status', table_name='spills')
    op.drop_index('idx_spills_spill_polygon', table_name='spills', postgresql_using='gist')
    op.drop_index('idx_spills_scene', table_name='spills')
    op.drop_table('spills')
    op.drop_index('idx_ais_gaps_vessel', table_name='ais_gaps')
    op.drop_index('idx_ais_gaps_time', table_name='ais_gaps')
    op.drop_index('idx_ais_gaps_next_position', table_name='ais_gaps', postgresql_using='gist')
    op.drop_index('idx_ais_gaps_last_position', table_name='ais_gaps', postgresql_using='gist')
    op.drop_index('idx_ais_gaps_gap_center', table_name='ais_gaps', postgresql_using='gist')
    op.drop_table('ais_gaps')
    op.drop_index('idx_vessels_type', table_name='vessels')
    op.drop_index('idx_vessels_mmsi', table_name='vessels', postgresql_where=sa.text('mmsi IS NOT NULL'))
    op.drop_index('idx_vessels_imo', table_name='vessels', postgresql_where=sa.text('imo IS NOT NULL'))
    op.drop_table('vessels')
    op.drop_index('idx_scenes_provider_external', table_name='scenes')
    op.drop_index('idx_scenes_footprint', table_name='scenes', postgresql_using='gist')
    op.drop_index('idx_scenes_captured_at', table_name='scenes')
    op.drop_table('scenes')
    op.drop_index('idx_jobs_type', table_name='jobs')
    op.drop_index('idx_jobs_status', table_name='jobs')
    op.drop_index('idx_jobs_idempotency', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index('idx_env_source_var_time', table_name='environmental_data')
    op.drop_index('idx_env_location', table_name='environmental_data', postgresql_using='gist')
    op.drop_table('environmental_data')
    op.drop_index('idx_audit_occurred_at', table_name='audit_log')
    op.drop_index('idx_audit_entity', table_name='audit_log')
    op.drop_index('idx_audit_actor', table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
